import pymysql, ssl
ctx = ssl.create_default_context(cafile='tidb-ca.pem')
conn = pymysql.connect(host='gateway01.ap-northeast-1.prod.aws.tidbcloud.com', user='2bQTqZhCnsH42Ss.root', password='gNnYDF8UbAFqx0Br', port=4000, database='bhagalpur_stays', ssl=ctx)
c = conn.cursor()
c.execute("ALTER TABLE hotels ADD COLUMN latitude DECIMAL(10,8)")
c.execute("ALTER TABLE hotels ADD COLUMN longitude DECIMAL(11,8)")
c.execute("ALTER TABLE hotels ADD COLUMN check_in_time TIME DEFAULT '14:00:00'")
c.execute("ALTER TABLE hotels ADD COLUMN check_out_time TIME DEFAULT '11:00:00'")
c.execute("ALTER TABLE hotels ADD COLUMN cancellation_hours INT DEFAULT 24")
c.execute("ALTER TABLE bookings ADD COLUMN coupon_id INT")
c.execute("ALTER TABLE bookings ADD COLUMN cancelled_at TIMESTAMP NULL")
c.execute("ALTER TABLE bookings ADD COLUMN cancellation_reason TEXT")
c.execute("ALTER TABLE bookings ADD COLUMN refund_amount DECIMAL(10,2) DEFAULT 0")
c.execute("ALTER TABLE reviews ADD COLUMN cleanliness_rating INT")
c.execute("ALTER TABLE reviews ADD COLUMN service_rating INT")
c.execute("ALTER TABLE reviews ADD COLUMN comfort_rating INT")
c.execute("ALTER TABLE reviews ADD COLUMN value_rating INT")
c.execute("ALTER TABLE reviews ADD COLUMN location_rating INT")
c.execute("ALTER TABLE payments ADD COLUMN gateway_response JSON")
c.execute("ALTER TABLE payments ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
conn.commit()
conn.close()
print('Columns added!')
